### ISSUE TITLE
TinyMCE Shadow DOM Support

### ISSUE THREAD

**Issue by tinydylan** [parttio/tinymce-for-flow#11]
Hi,

In your readme you note that TinyMCE doesn't work in Shadow DOM.

We've actually added some support for Shadow DOM in TinyMCE 5.5. I was wondering if you would like to test out your plugin with TinyMCE 5.5 and see if the Shadow DOM issues you've seen have gone or are still occurring. If you find any bugs, you can let me know in this issue, or in the [TinyMCE issue tracker](https://github.com/tinymce/tinymce/issues).

Kind regards,

Dylan Just
Tiny Technologies

**Comment by ado2000** [comment]
Hi, i did some tests with tinymce 5.5.1, seems OK.
Waiting to test the plugin ported to last tinymce.

Good job!

**Comment by tinydylan** [comment]
Fantastic!

**Comment by ado2000** [comment]
> Hi,
> 
> In your readme you note that TinyMCE doesn't work in Shadow DOM.
> 
> We've actually added some support for Shadow DOM in TinyMCE 5.5. I was wondering if you would like to test out your plugin with TinyMCE 5.5 and see if the Shadow DOM issues you've seen have gone or are still occurring. If you find any bugs, you can let me know in this issue, or in the [TinyMCE issue tracker](https://github.com/tinymce/tinymce/issues).
> 
> Kind regards,
> 
> Dylan Just
> Tiny Technologies

Hi, I've done other tests,

Tinymce works correctly in the dialog, but if the dialog is modal it does not run correctly.

The problem is related to the font menu, color menu etc ... if you move the mouse over the menu, the menu is not clickable

**Comment by techtangents** [comment]
Hi,

Many thanks for looking into this. If it's not too much to ask, are you able to please try to reproduce the issue at https://fiddle.tiny.cloud/? 

Unfortunately, we don't have any test environments or experience in Vaadin, so a replication would really help us get to the bottom of this.

Thanks again for your help. It's really appreciated.

Kind regards,
Dylan

**Comment by ado2000** [comment]
> Hi,
> 
> Many thanks for looking into this. If it's not too much to ask, are you able to please try to reproduce the issue at https://fiddle.tiny.cloud/?
> 
> Unfortunately, we don't have any test environments or experience in Vaadin, so a replication would really help us get to the bottom of this.
> 
> Thanks again for your help. It's really appreciated.
> 
> Kind regards,
> Dylan

Sorry, not able to reproduce it on fiddle, my app is written in java.

**Comment by TatuLund** [comment]
I think this ticket is outdated. The latest versions add-on for Vaadin 23 and 24 has been refactored so that Shadow DOM issue is avoided. Hence shadowRoot variant of the constructor has been marked deprecated

https://github.com/parttio/tinymce-for-flow/blob/master/src/main/java/org/vaadin/tinymce/TinyMce.java#L84
