### ISSUE TITLE
Your TinyMCE access will expire on 25th February 2021

### ISSUE THREAD

**Issue by kai83** [parttio/tinymce-for-flow#12]
Since today I am getting an warning saying tinyMCE access will expire on 25th of February.
Is there a plan to update to the latest version?

![image](https://user-images.githubusercontent.com/40805519/100920233-1af9e900-34db-11eb-8075-37fae33934ca.png)

**Comment by kai83** [comment]
As I needed a quick solution, I modified the URL now and added an access token.
This was just a quick solution and can be improved, but for now that worked.

**Comment by mstahv** [comment]
Fixed a while ago...
