### ISSUE TITLE
Focus problems in modal dialog

### ISSUE THREAD

**Issue by ghe-bm** [parttio/tinymce-for-flow#19]
Hi,

I try to use the Editor in a modal Dialog. I found out that I need to use the shadowRoot parameter if I want to do that. So, the menus/toolbars are now working as expected.
My current problem is the keyboard navigation in the modal dialog. When I use the TAB key to navigate through the elements, the editor content is not focused instead the editor is ignored and the next element is focused.
Is this a known Problem? Is there any workaround for it?

If I don't use a modal dialog it is working as expected.

Kind regards,
Gregor

**Comment by mstahv** [comment]
This is now fixed (nasty workwaround, but seems to work). 4.2.0 currrently in build pipeline.

**Comment by mstahv** [comment]
Note, that the shadow root parameter is no more needed (and deprecated).
