### ISSUE TITLE
Failing to load Theme/Model/Icons

### ISSUE THREAD

**Issue by MarkusPorti** [parttio/tinymce-for-flow#22]
Hello together,
I just tried to use this component inside my vaadin Project but can't get it to work and I really don't know what I'm missing.
For me it looks like a bug but I'm not sure if I have some errors in my configuration.

I imported the dependency in pom:
```
<dependency>
    <groupId>org.parttio</groupId>
    <artifactId>tinymce-for-flow</artifactId>
    <version>4.0.4</version>
</dependency>
```

Added following line in applications.properties:
`vaadin.whitelisted-packages = org.parttio, org.example, org.vaadin`

Created this simple class and added it to a View:
```
public class TopicContentEditor extends VerticalLayout {
    public TopicContentEditor() {
        setPadding(false);

        TinyMce editor = new TinyMce();
        editor.setEditorContent("<h1>Deckblatt</h1>");
        editor.setSizeFull();

        add(editor);
    }
}
```

But after building and starting the application I get some UI/frontend errors shown in vaadin-developement-tools:
![Screenshot 2023-10-16 142213](https://github.com/parttio/tinymce-for-flow/assets/49036454/e6b26708-36d2-41f2-81e0-25e056408c58)

What am I missing?
Could this be a problem or issue from your addon or do I have to configure something else?

Thanks for your help,
Markus

**Comment by mstahv** [comment]
Looks like the scripts are loaded from a wrong directory 🤔

**Comment by mstahv** [comment]
Wasn't able to reproduce right away even if putting in a longer deep linking url to the view. Is that some kind of embedded app?

**Comment by mstahv** [comment]
Got it, it happens with multi slash urls, in case one lands directly to such views.

**Comment by MarkusPorti** [comment]
Yes, I just thought about that too. My Route is defined with RouteParams and also the last one is optional:

`@Route(value = ":reportID/editTopic/:topicID?", layout = TopicsLayout.class)`

**Comment by mstahv** [comment]
Yup, my guess is if you navigate there from elsewhere from your app, it works. I think I have a valid fix, I'll still test that in an app that uses a special context path as well.

**Comment by mstahv** [comment]
Release build is in progress, in about 30 minutes, Maven central should have a version 4.0.5 available.
