### ISSUE TITLE
Update TinyMCE version for Vaadin 23.x version

### ISSUE THREAD

**Issue by ghe-bm** [parttio/tinymce-for-flow#24]
Hello,

we are using this add-on in version 3.3.2 in combination with Vaadin 23.3.27 in our application.
Last week our application was analysed by a pentesting company and they found out that we are using a TinyMCE Version with vulnerabilites (5.10.7).
I searched the TinyMCE website and saw that these were fixed in version 5.10.9.
Could you please build a new 3.x version of this add-on, including the latest TinyMCE version?

Best regards,
Gregor

**Comment by TatuLund** [comment]
Will be fixed by https://github.com/parttio/tinymce-for-flow/commit/6e246bb04ed430309bc58d11f1123288f70a81e7
