### ISSUE TITLE
Fous is not working in a dialog, neither programmatically nor navigating by keyboard

### ISSUE THREAD

**Issue by SonReimer** [parttio/tinymce-for-flow#28]
I can not set the focus in a dialog, neither by keyboard nor programmatic
Version 4.1.3/vaadin 24.3.2.

Testcase is the same as for https://github.com/parttio/tinymce-for-flow/issues/27

**Comment by mstahv** [comment]
Notes: Programatically (and with a keyboarshortcut) works, but getting the with tabulator seems to be an issue 🤷‍♂️

**Comment by mstahv** [comment]
That was a fight, reminds me of IE 5.5/6 JS hacks...

**Comment by SonReimer** [comment]
Hi Matti,
are there any plans for a 4.2.0 release containing this fix ?

**Comment by mstahv** [comment]
Oh, the release has been tagged but something wrong in the release build 🤔

**Comment by mstahv** [comment]
Triggered a new release. 4.2.1 should be on its way Maven central as we speak.

**Comment by SonReimer** [comment]
There is still no relase 4.2.1 this morning !?!
https://mvnrepository.com/artifact/org.parttio/tinymce-for-flow

**Comment by mstahv** [comment]
It is there, the mvnrepository.com service probably caches status:

https://central.sonatype.com/artifact/org.parttio/tinymce-for-flow
https://repo1.maven.org/maven2/org/parttio/tinymce-for-flow/

**Comment by SonReimer** [comment]
thx
