### ISSUE TITLE
Any way to call insert function ? 

### ISSUE THREAD

**Issue by ado2000** [parttio/tinymce-for-flow#3]
Hi, thanks for the component, 

is there any way to insert text at the caret position ?

It is possible by calling a js method like "tinymce.activeEditor.selection.setContent('html string');"

Thanks

**Comment by mstahv** [comment]
Hi!

I think that shouldn't be too hard to implement it. What is the use case? Where is the html string coming from (like automatically from background thread, separate button, keyboard shortcut) ?

**Comment by ado2000** [comment]
Hi,
the main use for us should be using a different button or combobox that adds ( on click/select )  some placeholder text into the html editor ad caret position, like %%user_name%% 

so, the user click into the editor on the point where they want to insert the placeholder, than click on the button or combobox to insert the placeholder.

Thanks

**Comment by mstahv** [comment]
I believe the change referred above helps you. Let me know if it don't. I'll cut a new release in next couple of minutes.

**Comment by mstahv** [comment]
1.4 should be synchronised to maven repository shortly.

**Comment by ado2000** [comment]
Hi Matti, 
sorry for the delay,

it works like a charm.

Thanks a lot.
