### ISSUE TITLE
onDetach JS error when setVisible(false)

### ISSUE THREAD

**Issue by marekmatus** [parttio/tinymce-for-flow#33]
First of all thanks for the addon :-)

After upgrade to vaadin 24:

When TinyMCE is added to a page but setVisible(false) then after onDetach a javascript error occurs: 
```
The error has occurred in the JS code: '$0, tinymce.get($0).remove(); '
Uncaught TypeError: tinymce.get(...) is null
```

Vaadin: 24.3.8
tinymce-for-flow: 4.2.2

**Comment by mstahv** [comment]
Fixed! @TatuLund You had some other fixes in queue or shall we cut a release?

**Comment by TatuLund** [comment]
I pushed my updates today, the master is upto date.

**Comment by mstahv** [comment]
A version with this fix in was already cut on friday.
