### ISSUE TITLE
replaceSelectionContent(String) does not set new Value for Editor

### ISSUE THREAD

**Issue by Eyvind-A** [parttio/tinymce-for-flow#40]
TinyMCE function replaceSelectionContent(String) does not fire change event resulting in that the value of the editor is not set with the new value.

**Comment by mstahv** [comment]
Hi! 

I guess this was some sort fo regression. Added a forced value sync after the method is called.

As the method relies on a JS call, the value is not on the server right after the call, but on next value change all should be fine. I'd expect this to be enough for "99%" of cases.

4.2.6 ought to be on its way to Maven central.
