### ISSUE TITLE
Upgrade TinyMCE to 4.9?

### ISSUE THREAD

**Issue by caseydlvr** [parttio/tinymce-for-flow#6]
Is there a technical reason this is still using TinyMCE 4.6 (4.6.7 from 9/2017) as opposed to a newer version of v4, such as 4.9 (4.9.6 from 9/2019)? There have been a lot of bug fixes since the latest version of 4.6.

**Comment by mstahv** [comment]
Don't really remember. Might be that the initial version is ranging as long back that it was the latest 4 series release at that point or then the newer didn't work for some reason. Did you try just upgrading to the latest from the 4.x series?

**Comment by caseydlvr** [comment]
I thought that might be the case. Was going to submit a PR for 4.9 as it was working for us, but I wanted to make sure there wasn't some compatibility reason to still be on 4.6. Thanks for the updates!!!
