### ISSUE TITLE
Is I18n possible?

### ISSUE THREAD

**Issue by sascha-broich** [parttio/tinymce-for-flow#7]
Is it possible to configure the language for TinyMCE?
It looks like there are additional files and a configuration object necessary: 
https://www.tiny.cloud/docs/configure/localization/

**Comment by sascha-broich** [comment]
Found the solution.
1. Download the localization file from [here](https://www.tiny.cloud/get-tiny/language-packages/), extract the js file and put it in the static web content
2. Use the TinyMce::setConfig method with 
`"{\"language_url\":\"<web content path>/<language>.js\"}"`

**Comment by windgaucho** [comment]
Can you please tell me where to put that file in a vaadin project? I can't get it to work. I am using vaadin 22.0.5

**Comment by sascha-broich** [comment]
Hm, I've not tried it with that version.
It should be placed where all your other static web stuff (CSS, JS, images) is, as [this section](https://vaadin.com/docs/latest/flow/advanced/loading-resources/#static-resources) explains. 
If that doesn't work, maybe, depending on what you have, it would be one of those two locations, as described [here](https://vaadin.com/docs/latest/flow/advanced/loading-resources):
* In non-Spring projects `/src/main/webapp/`
* In Spring projects and add-ons `/src/main/resources/META-INF/resources/`

**Comment by windgaucho** [comment]
Hi @sascha-broich, thanks for your response.
Yes I already try that locations, but with no success.

Can you please show me an example how your are using it? it would be of great help.
Thanks

**Comment by TatuLund** [comment]
There are bunch of localizations in the newest versions.

You can find the supported languages here: https://github.com/parttio/tinymce-for-flow/blob/master/src/main/java/org/vaadin/tinymce/Language.java

Example:

`tinymce.configureLanguage(Language.FRENCH);`
